### ISSUE TITLE
window decoration issue in linux

### ISSUE THREAD

**Issue by akashKarmakar02** [gen2brain/raylib-go#498]
```bash
libdecor-gtk-WARNING: Failed to initialize GTK
Failed to load plugin 'libdecor-gtk.so': failed to init
```

having this issue while running game from vs code or flatpak build

```yaml
- name: libdecor
    buildsystem: simple
    config-opts:
      - --prefix=/app
      - --libdir=lib64
      - --enable-gtk
      - --enable-gtk3
      - --enable-gtk4
    sources:
      - type: git
        url: https://gitlab.freedesktop.org/libdecor/libdecor.git
        branch: main
    build-commands:
      - meson _build --prefix=/app
      - ninja -C _build
      - ninja -C _build install
```

i am also adding libdecor in flatpak it only work if i run the binary outside of vs code
